
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.autolavado.view;

import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.edu.utxicotepec.autolavado.Controller.ClientesController;
import mx.edu.utxicotepec.autolavado.model.ClientesModel;
import mx.edu.utxicotepec.autolavado.model.UsuariosModel;

/**
 *
 * @author Yazmin Ariana
 */
public class FrmClientes extends javax.swing.JInternalFrame {

    private final DefaultTableModel modeloTabla;
    private int idClienteSeleccionado;
    private int idCliente = 0;

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        
        super("Formulario Usuarios", true, false, false, true);
            setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
            
        modeloTabla = new DefaultTableModel(new Object[]{"idCliente", "nombre", "primerApellido", "segundoApellido",
            "direccion", "telefono", "correo", "password"}, 0);
        
        initComponents();
        
        tblclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientesMouseClicked(evt);
            }
        });
        
        tblclientes.setModel(modeloTabla);
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDIreccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblapellidoP = new javax.swing.JLabel();
        txtapellidoP = new javax.swing.JTextField();
        lblapellidom = new javax.swing.JLabel();
        txtapellidoM = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        lblContraseña = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Clientes");

        jPanel6.setBackground(new java.awt.Color(33, 8, 190));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(1440, 1024));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setPreferredSize(new java.awt.Dimension(15, 25));

        lblnombre.setBackground(new java.awt.Color(0, 0, 255));
        lblnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(0, 0, 0));
        lblnombre.setText("Nombre: ");

        lblDireccion.setBackground(new java.awt.Color(0, 0, 255));
        lblDireccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Direccion:");

        txtDIreccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDIreccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDIreccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDIreccion.setPreferredSize(new java.awt.Dimension(15, 25));
        txtDIreccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIreccionActionPerformed(evt);
            }
        });

        lblTelefono.setBackground(new java.awt.Color(0, 0, 255));
        lblTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("Telefono:");

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setMinimumSize(new java.awt.Dimension(15, 25));

        lblCorreo.setBackground(new java.awt.Color(0, 0, 255));
        lblCorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setMinimumSize(new java.awt.Dimension(15, 25));

        lblapellidoP.setBackground(new java.awt.Color(0, 0, 255));
        lblapellidoP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblapellidoP.setForeground(new java.awt.Color(0, 0, 0));
        lblapellidoP.setText("Primer Apellido:");

        txtapellidoP.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtapellidoP.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidoP.setPreferredSize(new java.awt.Dimension(15, 25));

        lblapellidom.setBackground(new java.awt.Color(0, 0, 255));
        lblapellidom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblapellidom.setForeground(new java.awt.Color(0, 0, 0));
        lblapellidom.setText("Segundo Apellido:");

        txtapellidoM.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtapellidoM.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidoM.setPreferredSize(new java.awt.Dimension(15, 25));
        txtapellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoMActionPerformed(evt);
            }
        });

        txtContra.setBackground(new java.awt.Color(255, 255, 255));
        txtContra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtContra.setForeground(new java.awt.Color(0, 0, 0));

        lblContraseña.setBackground(new java.awt.Color(0, 0, 255));
        lblContraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña.setText("Contraseña:");
        lblContraseña.setPreferredSize(new java.awt.Dimension(89, 19));

        tblclientes.setBackground(new java.awt.Color(255, 255, 255));
        tblclientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblclientes.setForeground(new java.awt.Color(0, 0, 0));
        tblclientes.setModel(modeloTabla);
        jScrollPane3.setViewportView(tblclientes);

        jToolBar1.setRollover(true);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Agregar.png")); // NOI18N
        btnnuevo.setText("Agregar");
        btnnuevo.setFocusable(false);
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnuevo);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Guardar.png")); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnguardar);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Buscar.png")); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbuscar);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(0, 0, 0));
        btnmodificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Modificar.png")); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setFocusable(false);
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnmodificar);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblapellidoP)
                                    .addComponent(lblapellidom))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDireccion)
                                    .addComponent(lblnombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addGap(69, 69, 69)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCorreo)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblapellidoP)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre))
                        .addGap(18, 18, 18)
                        .addComponent(txtapellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblapellidom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion))))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDIreccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIreccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIreccionActionPerformed

    private void txtapellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoMActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        buscarcliente();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        eliminarcliente();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        agregarClientes();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        modificarcliente();
    }//GEN-LAST:event_btnmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    public void agregarClientes() {
        String nombre = txtnombre.getText();
        String primerApellido = txtapellidoP.getText();
        String segundoApellido = txtapellidoM.getText();
        String direccion = txtDIreccion.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String contra = txtContra.getText();

        if (nombre.isEmpty() || primerApellido.isEmpty() || segundoApellido.isEmpty() || direccion.isEmpty()
                || telefono.isEmpty() || correo.isEmpty() || contra.isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Favor de ingresar los datos en las cajas de texto vacias.");
            return;
        }

        ClientesModel nuevoCliente = new ClientesModel(nombre, primerApellido, segundoApellido, direccion, telefono, correo, contra);

        if (ClientesController.insertarClientes(nuevoCliente)) {
            txtnombre.setText("");
            txtapellidoP.setText("");
            txtapellidoM.setText("");
            txtDIreccion.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
            txtContra.setText("");
            cargarClientes();
        }
    }

    public void cargarClientes() {
        modeloTabla.setRowCount(0);
        List<ClientesModel> clientes = ClientesController.mostrarTodos();
        for (ClientesModel c : clientes) {
            modeloTabla.addRow(new Object[]{c.getIdCliente(), c.getNombre(), c.getPrimerApellido(), c.getSegundoApellido(), c.getDireccion(), c.getTelefono(),
                c.getCorreo(), c.getPassword()});
        }
    }

    public void buscarcliente() {
        String terminoBusqueda = JOptionPane.showInputDialog(this, "Ingrese el nombre o apellido del cliente", "Buscar cliente", JOptionPane.QUESTION_MESSAGE);

        if (terminoBusqueda == null || terminoBusqueda.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre o apellido para buscar.");
            return;
        }

        modeloTabla.setRowCount(0);

        List<ClientesModel> clientesEncontrados = ClientesController.buscarclientesPorTermino(terminoBusqueda);

        if (!clientesEncontrados.isEmpty()) {
            for (ClientesModel c : clientesEncontrados) {
                modeloTabla.addRow(new Object[]{c.getIdCliente(), c.getNombre(), c.getPrimerApellido(), c.getSegundoApellido(),
                    c.getDireccion(), c.getTelefono(), c.getCorreo(), c.getPassword()});
            }
            JOptionPane.showMessageDialog(this, clientesEncontrados.size() + " cliente/s encontrado/s.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron clientes con ese nombre o apellido.");
        }
    }

    private void tblclientesMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tblclientes.getSelectedRow();
        if (fila != -1) {
            idClienteSeleccionado = (int) tblclientes.getValueAt(fila, 0);

            txtnombre.setText(tblclientes.getValueAt(fila, 1).toString());
            txtapellidoP.setText(tblclientes.getValueAt(fila, 2).toString());
            txtapellidoM.setText(tblclientes.getValueAt(fila, 3).toString());
            txtDIreccion.setText(tblclientes.getValueAt(fila, 4).toString());
            txtTelefono.setText(tblclientes.getValueAt(fila, 5).toString());
            txtCorreo.setText(tblclientes.getValueAt(fila, 6).toString());
            txtContra.setText(tblclientes.getValueAt(fila, 7).toString());

        }
    }

    public void modificarcliente() {
        if (idClienteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente para modificar.");
            return;
        }
        String nombre = txtnombre.getText();
        String primerApellido = txtapellidoP.getText();
        String segundoApellido = txtapellidoM.getText();
        String direccion = txtDIreccion.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String password = txtContra.getText();

        if (nombre.isEmpty() || primerApellido.isEmpty() || segundoApellido.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos obligatorios.");
            return;
        }

        ClientesModel clientesModificado = new ClientesModel(
                idClienteSeleccionado,
                nombre,
                primerApellido,
                segundoApellido,
                direccion,
                telefono,
                correo,
                password
        );

        boolean exito = ClientesController.modificarcliente(clientesModificado);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Cliente modificado exitosamente.");
            cargarClientes();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el cliente.");
        }
    }

    private void limpiarCampos() {
        txtnombre.setText("");
        txtapellidoP.setText("");
        txtapellidoM.setText("");
        txtDIreccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtContra.setText("");
    }

    public void eliminarcliente() {
        if (idClienteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este usuario?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.NO_OPTION) {
            return;
        }
        boolean exito = ClientesController.eliminarCliente(idClienteSeleccionado);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");
            cargarClientes(); // Recarga los datos de la tabla para que el cambio sea visible
            limpiarCampos(); // Limpia el formulario después de la eliminación
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblapellidoP;
    private javax.swing.JLabel lblapellidom;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTable tblclientes;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDIreccion;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtapellidoM;
    private javax.swing.JTextField txtapellidoP;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
