/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.autolavado.view;

import javax.swing.JOptionPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Yazmin Ariana
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuusuarios = new javax.swing.JMenu();
        submnuRols = new javax.swing.JMenuItem();
        submnuUsuarios = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        submnuClientes = new javax.swing.JMenuItem();
        submnuVehiculos = new javax.swing.JMenuItem();
        mnuServicios = new javax.swing.JMenu();
        submnuServicios = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        submnuVentas = new javax.swing.JMenuItem();
        submnuSalir = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido al Sistema");

        Desktop.setPreferredSize(new java.awt.Dimension(1440, 1024));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        mnuusuarios.setBackground(new java.awt.Color(255, 255, 255));
        mnuusuarios.setForeground(new java.awt.Color(0, 0, 0));
        mnuusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuariosC.png"))); // NOI18N
        mnuusuarios.setText("Usuarios");
        mnuusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuusuariosActionPerformed(evt);
            }
        });

        submnuRols.setText("Registrar Rols");
        submnuRols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuRolsActionPerformed(evt);
            }
        });
        mnuusuarios.add(submnuRols);

        submnuUsuarios.setText("Registrar Usuarios");
        submnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuUsuariosActionPerformed(evt);
            }
        });
        mnuusuarios.add(submnuUsuarios);

        jMenuBar1.add(mnuusuarios);

        mnuClientes.setBackground(new java.awt.Color(255, 255, 255));
        mnuClientes.setForeground(new java.awt.Color(0, 0, 0));
        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clienteC.png"))); // NOI18N
        mnuClientes.setText("Clientes");

        submnuClientes.setText("Registrar Clientes");
        submnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuClientesActionPerformed(evt);
            }
        });
        mnuClientes.add(submnuClientes);

        submnuVehiculos.setText("Registrar Vehiculos");
        submnuVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuVehiculosActionPerformed(evt);
            }
        });
        mnuClientes.add(submnuVehiculos);

        jMenuBar1.add(mnuClientes);

        mnuServicios.setBackground(new java.awt.Color(255, 255, 255));
        mnuServicios.setForeground(new java.awt.Color(0, 0, 0));
        mnuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviciosC.png"))); // NOI18N
        mnuServicios.setText("Servicios");

        submnuServicios.setText("Registrar Servicios");
        submnuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuServiciosActionPerformed(evt);
            }
        });
        mnuServicios.add(submnuServicios);

        jMenuBar1.add(mnuServicios);

        mnuVentas.setBackground(new java.awt.Color(255, 255, 255));
        mnuVentas.setForeground(new java.awt.Color(0, 0, 0));
        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventasC.png"))); // NOI18N
        mnuVentas.setText("Ventas");

        submnuVentas.setText("Realizar Venta");
        submnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuVentasActionPerformed(evt);
            }
        });
        mnuVentas.add(submnuVentas);

        jMenuBar1.add(mnuVentas);

        submnuSalir.setBackground(new java.awt.Color(255, 255, 255));
        submnuSalir.setForeground(new java.awt.Color(0, 0, 0));
        submnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salirC.png"))); // NOI18N
        submnuSalir.setText("Salir");
        submnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuSalirActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Salir del sistema");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        submnuSalir.add(jMenuItem6);

        jMenuBar1.add(submnuSalir);

        mnuAyuda.setBackground(new java.awt.Color(255, 255, 255));
        mnuAyuda.setForeground(new java.awt.Color(0, 0, 0));
        mnuAyuda.setText("Ayuda");
        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuUsuariosActionPerformed
        // TODO add your handling code here:
        FrmUsuarios formusaurios = new FrmUsuarios();
        Desktop.add(formusaurios);
        formusaurios.setVisible(true);
    }//GEN-LAST:event_submnuUsuariosActionPerformed

    private void submnuRolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuRolsActionPerformed
        // TODO add your handling code here:
        FrmRols formrols = new FrmRols();
        Desktop.add(formrols);
        formrols.setVisible(true);
    }//GEN-LAST:event_submnuRolsActionPerformed

    private void mnuusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuusuariosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuusuariosActionPerformed

    private void submnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuClientesActionPerformed
        // TODO add your handling code here:
        FrmClientes formclientes = new FrmClientes();
        Desktop.add(formclientes);
        formclientes.setVisible(true);
    }//GEN-LAST:event_submnuClientesActionPerformed

    private void submnuVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuVehiculosActionPerformed
        // TODO add your handling code here:
        FrmVehiculos formvehiculos = new FrmVehiculos();
        Desktop.add(formvehiculos);
        formvehiculos.setVisible(true);
    }//GEN-LAST:event_submnuVehiculosActionPerformed

    private void submnuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuServiciosActionPerformed
        // TODO add your handling code here:
        FrmServicios formservicios = new FrmServicios();
        Desktop.add(formservicios);
        formservicios.setVisible(true);
    }//GEN-LAST:event_submnuServiciosActionPerformed

    private void submnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuVentasActionPerformed
        // TODO add your handling code here:
        FrmVenta formventas = new FrmVenta();
        Desktop.add(formventas);
        formventas.setVisible(true);
    }//GEN-LAST:event_submnuVentasActionPerformed

    private void submnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuSalirActionPerformed

    }//GEN-LAST:event_submnuSalirActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuServicios;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenu mnuusuarios;
    private javax.swing.JMenuItem submnuClientes;
    private javax.swing.JMenuItem submnuRols;
    private javax.swing.JMenu submnuSalir;
    private javax.swing.JMenuItem submnuServicios;
    private javax.swing.JMenuItem submnuUsuarios;
    private javax.swing.JMenuItem submnuVehiculos;
    private javax.swing.JMenuItem submnuVentas;
    // End of variables declaration//GEN-END:variables
}
