/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.autolavado.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.edu.utxicotepec.autolavado.Controller.ServiciosController;
import mx.edu.utxicotepec.autolavado.model.ServiciosModel;

/**
 *
 * @author Yazmin Ariana
 */
public class FrmServicios extends javax.swing.JInternalFrame {

    private final DefaultTableModel modeloTabla;
    private int idServicioSeleccionado;
    private int idServiicios = 0;

    /**
     * Creates new form FrmServicios
     */
    public FrmServicios() {
        super("Formulario Servicios", true, false, false, true);

        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        modeloTabla = new DefaultTableModel(new Object[]{"idServiicios", "nombreServicio", "descripcion", "precio", "estatus"}, 0);

        initComponents();

        comboestatus.addItem("Activo");
        comboestatus.addItem("Inactivo");

        tblregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblserviciosMouseClicked(evt);
            }
        });
        tblregistro.setModel(modeloTabla);
        cargarServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbldescripcion = new javax.swing.JLabel();
        txtServicio1 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        lblestatus = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        txtprecio1 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        comboestatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblregistro = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Servicios");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbldescripcion.setBackground(new java.awt.Color(16, 227, 224));
        lbldescripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbldescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lbldescripcion.setText("Descripcion:");

        txtServicio1.setBackground(new java.awt.Color(16, 227, 224));
        txtServicio1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtServicio1.setForeground(new java.awt.Color(0, 0, 0));
        txtServicio1.setText("Nombre:");

        txtdescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtdescripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 0, 0));

        lblestatus.setBackground(new java.awt.Color(16, 227, 224));
        lblestatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblestatus.setForeground(new java.awt.Color(0, 0, 0));
        lblestatus.setText("Estatus:");

        lblprecio1.setBackground(new java.awt.Color(16, 227, 224));
        lblprecio1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblprecio1.setForeground(new java.awt.Color(0, 0, 0));
        lblprecio1.setText("Precio:");

        txtprecio1.setBackground(new java.awt.Color(255, 255, 255));
        txtprecio1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtprecio1.setForeground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Agregar.png")); // NOI18N
        btnnuevo.setText("Agregar");
        btnnuevo.setFocusable(false);
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnuevo);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Guardar.png")); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnguardar);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Buscar.png")); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbuscar);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(0, 0, 0));
        btnmodificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Modificar.png")); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setFocusable(false);
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnmodificar);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));

        comboestatus.setBackground(new java.awt.Color(255, 255, 255));
        comboestatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboestatus.setForeground(new java.awt.Color(0, 0, 0));
        comboestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboestatusActionPerformed(evt);
            }
        });

        tblregistro.setBackground(new java.awt.Color(255, 255, 255));
        tblregistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblregistro.setForeground(new java.awt.Color(0, 0, 0));
        tblregistro.setModel(modeloTabla);
        jScrollPane2.setViewportView(tblregistro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldescripcion)
                            .addComponent(txtServicio1)
                            .addComponent(lblprecio1)
                            .addComponent(lblestatus))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprecio1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(comboestatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        agregarServicios();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        buscarservicio();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        modificarservicio();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        eliminarServicio();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void comboestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboestatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServicios().setVisible(true);
            }
        });
    }

    public void agregarServicios() {
        String nombre = txtnombre.getText();
        String descripcion = txtdescripcion.getText();
        String precio = txtprecio1.getText();
        String estatus = (String) comboestatus.getSelectedItem();

        if (nombre.isEmpty() || descripcion.isEmpty() || precio.isEmpty() || estatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor de ingresar los datos en las cajas de texto");
            return;
        }

        ServiciosModel nuevoServicio = new ServiciosModel(nombre, descripcion, precio, estatus);

        if (ServiciosController.insertarServicios(nuevoServicio)) {
            txtnombre.setText("");
            txtdescripcion.setText("");
            txtprecio1.setText("");
            txtServicio1.setText("");
                cargarServicios();
        }
    }

    public void cargarServicios() {
        modeloTabla.setRowCount(0);
        List<ServiciosModel> servicios = ServiciosController.mostrarTodos();
        for (ServiciosModel s : servicios) {
            modeloTabla.addRow(new Object[]{s.getIdServiicios(), s.getNombreServicio(), s.getDescripcion(), s.getPrecio(), s.getEstatus()});
        }
    }

    public void buscarservicio() {
        String terminoBusqueda = JOptionPane.showInputDialog(this, "Ingrese el nombre", "Buscar servicio", JOptionPane.QUESTION_MESSAGE);

        if (terminoBusqueda == null || terminoBusqueda.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para buscar.");
            return;
        }

        modeloTabla.setRowCount(0);

        List<ServiciosModel> servicioEncontrados = ServiciosController.buscarservicioportermino(terminoBusqueda);

        if (!servicioEncontrados.isEmpty()) {
            for (ServiciosModel s : servicioEncontrados) {
                modeloTabla.addRow(new Object[]{s.getIdServiicios(), s.getNombreServicio(), s.getDescripcion(), s.getPrecio(), s.getEstatus()});
            }
            JOptionPane.showMessageDialog(this, servicioEncontrados.size() + "servicio encontrado");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro un servicio con este nombre");
        }
    }

    private void tblserviciosMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tblregistro.getSelectedRow();
        if (fila >= 0) {
            idServicioSeleccionado = (int) tblregistro.getValueAt(fila, 0);

            txtnombre.setText(tblregistro.getValueAt(fila, 1).toString());
            txtdescripcion.setText(tblregistro.getValueAt(fila, 2).toString());
            txtprecio1.setText(tblregistro.getValueAt(fila, 3).toString());

            String estatusSeleccionado = tblregistro.getValueAt(fila, 4).toString();

            comboestatus.setSelectedItem(estatusSeleccionado);
        }
    }

    public void modificarservicio() {
        if (idServicioSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio a modificar");
            return;
        }
        String nombre = txtnombre.getText();
        String descripcion = txtdescripcion.getText();
        String precio = txtprecio1.getText();
        String estatus = (String) comboestatus.getSelectedItem();

        if (nombre.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos obligatorios.");
            return;
        }

        ServiciosModel servicioModificado = new ServiciosModel(
                idServicioSeleccionado,
                nombre,
                descripcion,
                precio,
                estatus
        );

        boolean exito = ServiciosController.modificarServicio(servicioModificado);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Servicio modificado exitosamente.");
            cargarServicios();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el servicio.");
        }
    }

    public void eliminarServicio() {
        if (idServicioSeleccionado== -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este usuario?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.NO_OPTION) {
            return;
        }
        boolean exito = ServiciosController.eliminarServicio(idServicioSeleccionado);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");
            cargarServicios(); // Recarga los datos de la tabla para que el cambio sea visible
            limpiarCampos(); // Limpia el formulario después de la eliminación
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtnombre.setText("");
        txtdescripcion.setText("");
        txtprecio1.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> comboestatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblestatus;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JTable tblregistro;
    private javax.swing.JLabel txtServicio1;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio1;
    // End of variables declaration//GEN-END:variables
}
