/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.autolavado.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import mx.edu.utxicotepec.autolavado.Controller.RolController;
import mx.edu.utxicotepec.autolavado.Controller.UsuariosController;
import mx.edu.utxicotepec.autolavado.model.RolModel;
import mx.edu.utxicotepec.autolavado.model.UsuariosModel;

/**
 *
 * @author Yazmin Ariana
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private RolController rolController;
    private int idUsuarioSeleccionado;
    private int idUsuario = 0;
    private int idRolObtenido = 1;

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        super("Formulario Usuarios", true, false, false, true);
        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        modeloTabla = new DefaultTableModel(new Object[]{"idUsuario", "nombre", "primerApellido", "segundoApellido",
            "direccion", "telefono", "correo", "usuario", "password", "fechaNacimiento", "Rol"}, 0);

        initComponents();
        tblusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblusuariosMouseClicked(evt);
            }
        });
        rolController = new RolController();
        tblusuarios.setModel(modeloTabla);
        cargarRolesenCombobox();
        cargarUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lblnombre5 = new javax.swing.JLabel();
        lblapellidoP5 = new javax.swing.JLabel();
        lblapellidom5 = new javax.swing.JLabel();
        lblDireccion5 = new javax.swing.JLabel();
        lblTelefono5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtDIreccion = new javax.swing.JTextField();
        txtapellidoM = new javax.swing.JTextField();
        txtapellidoP = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblContraseña5 = new javax.swing.JLabel();
        lblfecha1 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        comborol = new javax.swing.JComboBox<>();
        txtContra = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblusuarios = new javax.swing.JTable();
        txtusuario = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        txtmes = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Usuarios");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        jToolBar1.setRollover(true);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Agregar.png")); // NOI18N
        btnnuevo.setText("Agregar");
        btnnuevo.setFocusable(false);
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnuevo);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Guardar.png")); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnguardar);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Buscar.png")); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbuscar);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(0, 0, 0));
        btnmodificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Modificar.png")); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setFocusable(false);
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnmodificar);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        lblnombre5.setBackground(new java.awt.Color(0, 0, 255));
        lblnombre5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblnombre5.setForeground(new java.awt.Color(0, 0, 0));
        lblnombre5.setText("Nombre: ");

        lblapellidoP5.setBackground(new java.awt.Color(0, 0, 255));
        lblapellidoP5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblapellidoP5.setForeground(new java.awt.Color(0, 0, 0));
        lblapellidoP5.setText("Primer Apellido:");

        lblapellidom5.setBackground(new java.awt.Color(0, 0, 255));
        lblapellidom5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblapellidom5.setForeground(new java.awt.Color(0, 0, 0));
        lblapellidom5.setText("Segundo Apellido:");

        lblDireccion5.setBackground(new java.awt.Color(0, 0, 255));
        lblDireccion5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDireccion5.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion5.setText("Direccion:");

        lblTelefono5.setBackground(new java.awt.Color(0, 0, 255));
        lblTelefono5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTelefono5.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono5.setText("Telefono:");

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setMinimumSize(new java.awt.Dimension(15, 25));

        txtDIreccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDIreccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDIreccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDIreccion.setPreferredSize(new java.awt.Dimension(15, 25));
        txtDIreccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIreccionActionPerformed(evt);
            }
        });

        txtapellidoM.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtapellidoM.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidoM.setPreferredSize(new java.awt.Dimension(15, 25));
        txtapellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoMActionPerformed(evt);
            }
        });

        txtapellidoP.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtapellidoP.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidoP.setPreferredSize(new java.awt.Dimension(15, 25));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setPreferredSize(new java.awt.Dimension(15, 25));

        lblCorreo.setBackground(new java.awt.Color(0, 0, 255));
        lblCorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        lblusuario.setBackground(new java.awt.Color(0, 0, 255));
        lblusuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 0, 0));
        lblusuario.setText("Usuario:");
        lblusuario.setPreferredSize(new java.awt.Dimension(89, 19));

        lblContraseña5.setBackground(new java.awt.Color(0, 0, 255));
        lblContraseña5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContraseña5.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña5.setText("Contraseña:");
        lblContraseña5.setPreferredSize(new java.awt.Dimension(89, 19));

        lblfecha1.setBackground(new java.awt.Color(0, 0, 255));
        lblfecha1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblfecha1.setForeground(new java.awt.Color(0, 0, 0));
        lblfecha1.setText("Rol De Usuario:");
        lblfecha1.setPreferredSize(new java.awt.Dimension(89, 19));

        lblfecha.setBackground(new java.awt.Color(0, 0, 255));
        lblfecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(0, 0, 0));
        lblfecha.setText("Fecha De Nacimiento:");
        lblfecha.setPreferredSize(new java.awt.Dimension(89, 19));

        comborol.setBackground(new java.awt.Color(255, 255, 255));
        comborol.setForeground(new java.awt.Color(0, 0, 0));
        comborol.setSelectedItem(modeloTabla);
        comborol.setToolTipText("");
        comborol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comborolActionPerformed(evt);
            }
        });

        txtContra.setBackground(new java.awt.Color(255, 255, 255));
        txtContra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtContra.setForeground(new java.awt.Color(0, 0, 0));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setMinimumSize(new java.awt.Dimension(15, 25));

        tblusuarios.setBackground(new java.awt.Color(255, 255, 255));
        tblusuarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblusuarios.setForeground(new java.awt.Color(0, 0, 0));
        tblusuarios.setModel(modeloTabla);
        jScrollPane3.setViewportView(tblusuarios);

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario.setMinimumSize(new java.awt.Dimension(15, 25));

        txtaño.setBackground(new java.awt.Color(255, 255, 255));
        txtaño.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtaño.setForeground(new java.awt.Color(0, 0, 0));
        txtaño.setToolTipText("");
        txtaño.setMinimumSize(new java.awt.Dimension(15, 25));
        txtaño.setPreferredSize(new java.awt.Dimension(15, 25));

        txtdia.setBackground(new java.awt.Color(255, 255, 255));
        txtdia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtdia.setForeground(new java.awt.Color(0, 0, 0));
        txtdia.setToolTipText("");
        txtdia.setMinimumSize(new java.awt.Dimension(15, 25));
        txtdia.setPreferredSize(new java.awt.Dimension(15, 25));

        txtmes.setBackground(new java.awt.Color(255, 255, 255));
        txtmes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmes.setForeground(new java.awt.Color(0, 0, 0));
        txtmes.setToolTipText("");
        txtmes.setMinimumSize(new java.awt.Dimension(15, 25));
        txtmes.setPreferredSize(new java.awt.Dimension(15, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblnombre5)
                            .addGap(48, 48, 48))
                        .addComponent(lblapellidoP5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapellidom5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion5)
                            .addComponent(lblTelefono5))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseña5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContra)
                                    .addComponent(comborol, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtaño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapellidoP5)
                            .addComponent(txtapellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblapellidom5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDIreccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion5))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContraseña5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comborol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        buscarusuario();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        eliminarusuario();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtDIreccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIreccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIreccionActionPerformed

    private void txtapellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoMActionPerformed

    private void comborolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comborolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comborolActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        agregarUsuarios();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        modificarUsuarios();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    public void cargarRolesenCombobox() {
        DefaultComboBoxModel<RolModel> comboModel = new DefaultComboBoxModel<>();
        List<RolModel> roles = rolController.obtenertodoslosrols();
        if (roles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron roles en la base de datos");
            comborol.setEnabled(false);
            btnguardar.setEnabled(false);
        } else {
            for (RolModel rol : roles) {
                comboModel.addElement(rol);
            }
            comborol.setModel(comboModel);
            comborol.setSelectedIndex(0);
            comborol.setEnabled(true);
            btnguardar.setEnabled(true);
        }
    }

    public void agregarUsuarios() {

        String nombre = txtnombre.getText();
        String primerApellido = txtapellidoP.getText();
        String segundoApellido = txtapellidoM.getText();
        String direccion = txtDIreccion.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String usuario = txtusuario.getText();
        String password = txtContra.getText();
        String fechaNacimiento = txtaño.getText() + "-" + txtmes.getText() + "-" + txtdia.getText();

        if (comborol.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol de usuario.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idRol = -1;

        // Casteo seguro para obtener el RolModel del JComboBox
        if (comborol.getSelectedItem() instanceof mx.edu.utxicotepec.autolavado.model.RolModel) {
            mx.edu.utxicotepec.autolavado.model.RolModel rolSeleccionado = (mx.edu.utxicotepec.autolavado.model.RolModel) comborol.getSelectedItem();
            idRol = rolSeleccionado.getIdRol();
        } else {
            // Este caso no debería ocurrir si el comborol está correctamente declarado y cargado
            JOptionPane.showMessageDialog(this, "Error interno: El elemento seleccionado no es un RolModel válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombre.isEmpty() || primerApellido.isEmpty() || segundoApellido.isEmpty() || direccion.isEmpty() || telefono.isEmpty()
                || correo.isEmpty() || usuario.isEmpty() || password.isEmpty() || fechaNacimiento.isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Favor de ingresar los datos en las cajas de texto vacias.");
            return;
        }

        UsuariosModel nuevoUsuario = new UsuariosModel(idRol, nombre, primerApellido, segundoApellido, direccion, telefono, correo, usuario, password, fechaNacimiento);

        if (UsuariosController.insertarUsuarios(nuevoUsuario)) {
            txtnombre.setText("");
            txtapellidoP.setText("");
            txtapellidoM.setText("");
            txtDIreccion.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
            txtusuario.setText("");
            txtContra.setText("");
            txtaño.setText("");
            txtmes.setText("");
            txtdia.setText("");
            cargarUsuarios();
        }
    }

    public void cargarUsuarios() {
        modeloTabla.setRowCount(0);
        List<UsuariosModel> usuarios = UsuariosController.mostrarTodos();
        for (UsuariosModel u : usuarios) {
            modeloTabla.addRow(new Object[]{u.getIdUsuario(), u.getNombre(), u.getPrimerApellido(), u.getSegundoApellido(), u.getDireccion(), u.getTelefono(),
                u.getCorreo(), u.getUsuario(), u.getPassword(), u.getFechaNacimiento(), u.getNombreRolDisplay()});
        }
    }

    private void buscarusuario() {
        String terminoBusqueda = JOptionPane.showInputDialog(this, "Ingrese el nombre o apellido del usuario:", "Buscar usuario", JOptionPane.QUESTION_MESSAGE);

        if (terminoBusqueda == null || terminoBusqueda.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre o apellido para buscar.");
            return;
        }

        modeloTabla.setRowCount(0);

        List<UsuariosModel> usuariosEncontrados = UsuariosController.buscarUsuariosPorTermino(terminoBusqueda);

        if (!usuariosEncontrados.isEmpty()) {
            for (UsuariosModel u : usuariosEncontrados) {
                modeloTabla.addRow(new Object[]{u.getIdUsuario(), u.getNombre(), u.getPrimerApellido(), u.getSegundoApellido(), u.getDireccion(), u.getTelefono(),
                    u.getCorreo(), u.getUsuario(), u.getPassword(), u.getFechaNacimiento(), u.getNombreRolDisplay()});
            }
            JOptionPane.showMessageDialog(this, usuariosEncontrados.size() + " usuario/s encontrado/s.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron usuarios con ese nombre o apellido.");
        }
    }

    private void tblusuariosMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tblusuarios.getSelectedRow();
        if (fila != -1) {
            idUsuarioSeleccionado = (int) tblusuarios.getValueAt(fila, 0);

            txtnombre.setText(tblusuarios.getValueAt(fila, 1).toString());
            txtapellidoP.setText(tblusuarios.getValueAt(fila, 2).toString());
            txtapellidoM.setText(tblusuarios.getValueAt(fila, 3).toString());
            txtDIreccion.setText(tblusuarios.getValueAt(fila, 4).toString());
            txtTelefono.setText(tblusuarios.getValueAt(fila, 5).toString());
            txtCorreo.setText(tblusuarios.getValueAt(fila, 6).toString());
            txtusuario.setText(tblusuarios.getValueAt(fila, 7).toString());
            txtContra.setText(tblusuarios.getValueAt(fila, 8).toString());

            String fechaNacimiento = tblusuarios.getValueAt(fila, 9).toString();
            String[] partesFecha = fechaNacimiento.split("-");
            if (partesFecha.length == 3) {
                txtaño.setText(partesFecha[0]);
                txtmes.setText(partesFecha[1]);
                txtdia.setText(partesFecha[2]);
            }

            String nombreRol = tblusuarios.getValueAt(fila, 10).toString();
            DefaultComboBoxModel<RolModel> modeloRoles = (DefaultComboBoxModel<RolModel>) comborol.getModel();
            for (int i = 0; i < modeloRoles.getSize(); i++) {
                if (modeloRoles.getElementAt(i).getNombreRol().equals(nombreRol)) {
                    comborol.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    private void modificarUsuarios() {
        if (idUsuarioSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para modificar.");
            return;
        }
        String nombre = txtnombre.getText();
        String primerApellido = txtapellidoP.getText();
        String segundoApellido = txtapellidoM.getText();
        String direccion = txtDIreccion.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String usuario = txtusuario.getText();
        String password = txtContra.getText();

        String año = txtaño.getText();
        String mes = txtmes.getText();
        String dia = txtdia.getText();

        if (año.isEmpty() || mes.isEmpty() || dia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la fecha de nacimiento completa.");
            return;
        }
        String fechaNacimiento = año + "-" + mes + "-" + dia;

        RolModel rolSeleccionado = (RolModel) comborol.getSelectedItem();
        if (rolSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol.");
            return;
        }
        int idRol = rolSeleccionado.getIdRol();

        if (nombre.isEmpty() || primerApellido.isEmpty() || usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos obligatorios.");
            return;
        }

        UsuariosModel usuarioModificado = new UsuariosModel(
                idUsuarioSeleccionado,
                idRol,
                nombre,
                primerApellido,
                segundoApellido,
                direccion,
                telefono,
                correo,
                usuario,
                password,
                fechaNacimiento
        );

        boolean exito = UsuariosController.modificarUsuario(usuarioModificado);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Usuario modificado exitosamente.");
            cargarUsuarios();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el usuario.");
        }
    }

    private void limpiarCampos() {
        txtnombre.setText("");
        txtapellidoP.setText("");
        txtapellidoM.setText("");
        txtDIreccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtusuario.setText("");
        txtContra.setText("");
        txtaño.setText("");
        txtmes.setText("");
        
    }

    public void eliminarusuario() {
        if (idUsuarioSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este usuario?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.NO_OPTION) {
            return;
        }
        boolean exito = UsuariosController.eliminarUsuario(idUsuarioSeleccionado);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");
            cargarUsuarios(); // Recarga los datos de la tabla para que el cambio sea visible
            limpiarCampos(); // Limpia el formulario después de la eliminación
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<mx.edu.utxicotepec.autolavado.model.RolModel> comborol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblContraseña5;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion5;
    private javax.swing.JLabel lblTelefono5;
    private javax.swing.JLabel lblapellidoP5;
    private javax.swing.JLabel lblapellidom5;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JLabel lblnombre5;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTable tblusuarios;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDIreccion;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtapellidoM;
    private javax.swing.JTextField txtapellidoP;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
