/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.autolavado.view;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.edu.utxicotepec.autolavado.Controller.ServiciosController;
import mx.edu.utxicotepec.autolavado.Controller.UsuariosController;
import mx.edu.utxicotepec.autolavado.Controller.VehiculoController;
import mx.edu.utxicotepec.autolavado.Controller.VentaServicioController;
import mx.edu.utxicotepec.autolavado.model.ServiciosModel;
import mx.edu.utxicotepec.autolavado.model.UsuariosModel;
import mx.edu.utxicotepec.autolavado.model.VentaServicioModel;

/**
 *
 * @author Yazmin Ariana
 */
public class FrmVenta extends javax.swing.JInternalFrame {

    private final DefaultTableModel modeloTabla;
    private int idVentaAModificar = -1;

    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        super("Formulario Ventas", true, false, false, true);
        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);

        modeloTabla = new DefaultTableModel(new Object[]{"idVentaServicios", "idUsuarioC", "idUsuarioO", "idServicio", "idVehiculo", "fecha", "hora", "estatus", "pagado"}, 0);

        initComponents();

        // Correcta inicialización y asignación del MouseListener
        tblsv.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsvMouseClicked(evt);
            }
        });

        tblsv.setModel(modeloTabla);
        cargarCajeros();
        cargarLavadores();
        cargarServicios();
        cargarEstatus();
        cargarPago();
        cargarVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lbldescripcion = new javax.swing.JLabel();
        lblcajero = new javax.swing.JLabel();
        txtvehiculo = new javax.swing.JTextField();
        lblestatus = new javax.swing.JLabel();
        lblservicio = new javax.swing.JLabel();
        txtdia = new javax.swing.JTextField();
        lbllavador = new javax.swing.JLabel();
        lblestatus1 = new javax.swing.JLabel();
        lblestatus2 = new javax.swing.JLabel();
        lblestatus3 = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        comboservicio = new javax.swing.JComboBox<>();
        combolavador = new javax.swing.JComboBox<>();
        txtmes = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        txtminutos = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsv = new javax.swing.JTable();
        combopago = new javax.swing.JComboBox<>();
        comboesattus = new javax.swing.JComboBox<>();
        combocajero = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Ventas");

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbldescripcion.setBackground(new java.awt.Color(16, 227, 224));
        lbldescripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbldescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lbldescripcion.setText("Vehiculo");

        lblcajero.setBackground(new java.awt.Color(16, 227, 224));
        lblcajero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblcajero.setForeground(new java.awt.Color(0, 0, 0));
        lblcajero.setText("Cajero:");

        txtvehiculo.setBackground(new java.awt.Color(255, 255, 255));
        txtvehiculo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtvehiculo.setForeground(new java.awt.Color(0, 0, 0));

        lblestatus.setBackground(new java.awt.Color(16, 227, 224));
        lblestatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblestatus.setForeground(new java.awt.Color(0, 0, 0));
        lblestatus.setText("Fecha:");

        lblservicio.setBackground(new java.awt.Color(16, 227, 224));
        lblservicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblservicio.setForeground(new java.awt.Color(0, 0, 0));
        lblservicio.setText("Servicio:");

        txtdia.setBackground(new java.awt.Color(255, 255, 255));
        txtdia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtdia.setForeground(new java.awt.Color(0, 0, 0));

        lbllavador.setBackground(new java.awt.Color(16, 227, 224));
        lbllavador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbllavador.setForeground(new java.awt.Color(0, 0, 0));
        lbllavador.setText("Lavador:");

        lblestatus1.setBackground(new java.awt.Color(16, 227, 224));
        lblestatus1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblestatus1.setForeground(new java.awt.Color(0, 0, 0));
        lblestatus1.setText("Estatus:");

        lblestatus2.setBackground(new java.awt.Color(16, 227, 224));
        lblestatus2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblestatus2.setForeground(new java.awt.Color(0, 0, 0));
        lblestatus2.setText("Pago");

        lblestatus3.setBackground(new java.awt.Color(16, 227, 224));
        lblestatus3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblestatus3.setForeground(new java.awt.Color(0, 0, 0));
        lblestatus3.setText("Hora:");

        txthora.setBackground(new java.awt.Color(255, 255, 255));
        txthora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txthora.setForeground(new java.awt.Color(0, 0, 0));

        comboservicio.setBackground(new java.awt.Color(255, 255, 255));
        comboservicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboservicio.setForeground(new java.awt.Color(0, 0, 0));
        comboservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboservicioActionPerformed(evt);
            }
        });

        combolavador.setBackground(new java.awt.Color(255, 255, 255));
        combolavador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combolavador.setForeground(new java.awt.Color(0, 0, 0));
        combolavador.setToolTipText("");

        txtmes.setBackground(new java.awt.Color(255, 255, 255));
        txtmes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmes.setForeground(new java.awt.Color(0, 0, 0));

        txtaño.setBackground(new java.awt.Color(255, 255, 255));
        txtaño.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtaño.setForeground(new java.awt.Color(0, 0, 0));

        txtminutos.setBackground(new java.awt.Color(255, 255, 255));
        txtminutos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtminutos.setForeground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Agregar.png")); // NOI18N
        btnnuevo.setText("Agregar");
        btnnuevo.setFocusable(false);
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnuevo);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Guardar.png")); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnguardar);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Buscar.png")); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbuscar);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(0, 0, 0));
        btnmodificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Modificar.png")); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setFocusable(false);
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnmodificar);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        tblsv.setBackground(new java.awt.Color(255, 255, 255));
        tblsv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblsv.setForeground(new java.awt.Color(0, 0, 0));
        tblsv.setModel(modeloTabla);
        jScrollPane1.setViewportView(tblsv);

        combopago.setBackground(new java.awt.Color(255, 255, 255));
        combopago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combopago.setForeground(new java.awt.Color(0, 0, 0));

        comboesattus.setBackground(new java.awt.Color(255, 255, 255));
        comboesattus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboesattus.setForeground(new java.awt.Color(0, 0, 0));

        combocajero.setBackground(new java.awt.Color(255, 255, 255));
        combocajero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combocajero.setForeground(new java.awt.Color(0, 0, 0));
        combocajero.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcajero)
                    .addComponent(lblservicio)
                    .addComponent(lbllavador)
                    .addComponent(lbldescripcion))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(combolavador, 0, 1, Short.MAX_VALUE)
                    .addComponent(txtvehiculo)
                    .addComponent(comboservicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combocajero, 0, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblestatus)
                    .addComponent(lblestatus1)
                    .addComponent(lblestatus2)
                    .addComponent(lblestatus3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtminutos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(combopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboesattus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblestatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblestatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboesattus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblestatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combocajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllavador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combolavador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        agregarservicio();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void comboservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboservicioActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        buscarVentas();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        modificarVenta();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        eliminarVenta();
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    public void agregarservicio() {
        if (combocajero.getSelectedItem() == null || combolavador.getSelectedItem() == null || comboservicio.getSelectedItem() == null || comboesattus.getSelectedItem() == null || combopago.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una opción en todos los menús desplegables.", "Error validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Validar que los campos de texto no estén vacíos
        String vehiculoTexto = txtvehiculo.getText();

        if (vehiculoTexto.isEmpty()) { // Add validation for the vehicle text field
            JOptionPane.showMessageDialog(this, "Favor de ingresar los datos en las cajas de texto vacías.", "Error validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idVehiculo = VehiculoController.buscarIdVehiculoPorMatricula(vehiculoTexto);

        if (idVehiculo == 0) {
            JOptionPane.showMessageDialog(this, "El vehículo no existe en la base de datos. Por favor, regístrelo primero.", "Error de vehículo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Obtener los objetos y valores del formulario
        UsuariosModel cajeroSeleccionado = (UsuariosModel) combocajero.getSelectedItem();
        ServiciosModel servicioSeleccionado = (ServiciosModel) comboservicio.getSelectedItem();
        UsuariosModel lavadorSeleccionado = (UsuariosModel) combolavador.getSelectedItem();

        VentaServicioModel nuevaVenta = new VentaServicioModel();

        // Asignar IDs y otros valores.
        nuevaVenta.setIdUsuarioC(cajeroSeleccionado.getIdUsuario()); // Get ID from the JComboBox
        nuevaVenta.setIdUsuarioO(lavadorSeleccionado.getIdUsuario());
        nuevaVenta.setIdServicio(servicioSeleccionado.getIdServiicios());
        nuevaVenta.setIdVehiculo(idVehiculo);

        // NOTA: La tabla `tbc_venta_servicios` tiene un `idVehiculo`. Debes obtener
        // este valor del formulario. El valor `0` es solo un marcador.
        // 5. Formatear y asignar la fecha y hora
        String fecha = txtaño.getText() + "-" + txtmes.getText() + "-" + txtdia.getText();
        String hora = txthora.getText() + ":" + txtminutos.getText() + ":00";

        nuevaVenta.setFecha(fecha);
        nuevaVenta.setHora(hora);

        // 6. Asignar los valores de los ComboBox de Estatus y Pago
        nuevaVenta.setEstatus((String) comboesattus.getSelectedItem());
        nuevaVenta.setPagado((String) combopago.getSelectedItem());

        // 7. Insertar la venta en la base de datos
        if (VentaServicioController.insertarVentaS(nuevaVenta)) {
            JOptionPane.showMessageDialog(this, "Venta registrada con éxito.");
            limpiarCampos(); // Se recomienda llamar a este método para no repetir código
            cargarVenta();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la venta.");
        }
    }

    public void cargarVenta() {
        modeloTabla.setRowCount(0);
        List<VentaServicioModel> ventas = VentaServicioController.mostrarTodos();
        for (VentaServicioModel v : ventas) {
            modeloTabla.addRow(new Object[]{
                v.getIdVentaServicio(),
                v.getIdUsuarioC(),
                v.getIdUsuarioO(),
                v.getIdServicio(),
                v.getIdVehiculo(),
                v.getFecha(),
                v.getHora(),
                v.getEstatus(),
                v.getPagado()
            });
        }
    }

    public void cargarLavadores() {
        List<UsuariosModel> lavadores = UsuariosController.mostrarOperarios();
        combolavador.removeAllItems();
        for (UsuariosModel lavador : lavadores) {
            combolavador.addItem(lavador);
        }
    }

    public void cargarServicios() {
        // Llama al controlador para obtener la lista de servicios
        List<ServiciosModel> servicios = ServiciosController.mostrarTodos();

        // Limpia el ComboBox antes de agregar nuevos elementos
        comboservicio.removeAllItems();

        // Agrega cada servicio a la lista desplegable
        for (ServiciosModel servicio : servicios) {
            comboservicio.addItem(servicio);
        }
    }

    public void cargarEstatus() {
        comboesattus.removeAllItems();
        comboesattus.addItem("En espera");
        comboesattus.addItem("En proceso");
        comboesattus.addItem("Finalizado");
    }

    public void cargarPago() {
        combopago.removeAllItems();
        combopago.addItem("Pagado");
        combopago.addItem("Pendiente");
    }

    public void cargarCajeros() {
        List<UsuariosModel> cajeros = UsuariosController.mostrarCajero();
        combocajero.removeAllItems();
        for (UsuariosModel cajero : cajeros) {
            combocajero.addItem(cajero);
        }
    }

    public void buscarVentas() {
        String terminoBusqueda = JOptionPane.showInputDialog(this, "Ingrese la matrícula, nombre del cajero o lavador para buscar", "Buscar Ventas", JOptionPane.QUESTION_MESSAGE);

        if (terminoBusqueda == null || terminoBusqueda.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un término para buscar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Llamada al nuevo método en el controlador que busca por un solo término
        List<VentaServicioModel> resultados = VentaServicioController.buscarVentasPorTermino(terminoBusqueda);

        // Limpiar la tabla y mostrar los resultados
        modeloTabla.setRowCount(0);
        if (!resultados.isEmpty()) {
            for (VentaServicioModel v : resultados) {
                modeloTabla.addRow(new Object[]{
                    v.getIdVentaServicio(),
                    v.getIdUsuarioC(),
                    v.getIdUsuarioO(),
                    v.getIdServicio(),
                    v.getIdVehiculo(),
                    v.getFecha(),
                    v.getHora(),
                    v.getEstatus(),
                    v.getPagado()
                });
            }
            JOptionPane.showMessageDialog(this, resultados.size() + " Venta(s) encontrada(s).");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron ventas con esos criterios.");
        }
    }

    public void tblsvMouseClicked(java.awt.event.MouseEvent evt) {
        int filaSeleccionada = tblsv.getSelectedRow();

        if (filaSeleccionada != -1) {
            int idVenta = (int) tblsv.getValueAt(filaSeleccionada, 0);
            VentaServicioModel ventaParaModificar = VentaServicioController.obtenerVentaPorId(idVenta);

            if (ventaParaModificar != null) {
                // ... (resto de tu código para rellenar campos) ...

                // ¡CORRECCIÓN! Debes descomentar esta línea para que funcione la modificación.
                // Necesitas una variable de clase llamada 'idVentaAModificar'
                this.idVentaAModificar = idVenta;
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo obtener la información de la venta seleccionada.");
            }
        }
    }

    private void seleccionarServicioEnCombo(JComboBox<ServiciosModel> combo, int idServicio) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            ServiciosModel servicio = combo.getItemAt(i);
            if (servicio.getIdServiicios() == idServicio) {
                combo.setSelectedItem(servicio);
                break;
            }
        }
    }

    private void modificarVenta() {
        // 1. Validaciones iniciales
        if (idVentaAModificar == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una venta para modificar.");
            return;
        }

        if (combocajero.getSelectedItem() == null || combolavador.getSelectedItem() == null || comboservicio.getSelectedItem() == null || comboesattus.getSelectedItem() == null || combopago.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una opción en todos los menús desplegables.", "Error validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String vehiculoTexto = txtvehiculo.getText();
        String año = txtaño.getText();
        String mes = txtmes.getText();
        String dia = txtdia.getText();
        String hora = txthora.getText();
        String minutos = txtminutos.getText();

        if (vehiculoTexto.isEmpty() || año.isEmpty() || mes.isEmpty() || dia.isEmpty() || hora.isEmpty() || minutos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor de ingresar los datos en todas las cajas de texto.", "Error validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Obtener los valores del formulario
        int idCajero = ((UsuariosModel) combocajero.getSelectedItem()).getIdUsuario();
        int idLavador = ((UsuariosModel) combolavador.getSelectedItem()).getIdUsuario();
        int idServicio = ((ServiciosModel) comboservicio.getSelectedItem()).getIdServiicios();

        int idVehiculo = VehiculoController.buscarIdVehiculoPorMatricula(vehiculoTexto);

        if (idVehiculo == 0) {
            JOptionPane.showMessageDialog(this, "El vehículo no existe en la base de datos.", "Error de vehículo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fecha = año + "-" + mes + "-" + dia;
        String horaCompleta = hora + ":" + minutos + ":00";

        // 3. Crear el objeto VentaServicioModel con el ID del registro seleccionado
        VentaServicioModel ventaModificada = new VentaServicioModel();
        ventaModificada.setIdVentaServicio(idVentaAModificar);
        ventaModificada.setIdUsuarioC(idCajero);
        ventaModificada.setIdUsuarioO(idLavador);
        ventaModificada.setIdServicio(idServicio);
        ventaModificada.setIdVehiculo(idVehiculo);
        ventaModificada.setFecha(fecha);
        ventaModificada.setHora(horaCompleta);
        ventaModificada.setEstatus((String) comboesattus.getSelectedItem());
        ventaModificada.setPagado((String) combopago.getSelectedItem());

        // 4. Llamar al método del controlador para actualizar la base de datos
        if (VentaServicioController.actualizarVenta(ventaModificada)) {
            JOptionPane.showMessageDialog(this, "Venta modificada con éxito.");
            idVentaAModificar = -1; // Resetear la variable de control
            limpiarCampos();
            cargarVenta(); // Refrescar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar la venta.");
        }
    }

    private void limpiarCampos() {
        txtvehiculo.setText("");
        txtaño.setText("");
        txtmes.setText("");
        txtdia.setText("");
        txthora.setText("");
        txtminutos.setText("");
        combocajero.setSelectedIndex(0);
        combolavador.setSelectedIndex(0);
        comboservicio.setSelectedIndex(0);
        comboesattus.setSelectedIndex(0);
        combopago.setSelectedIndex(0);
    }

    private void eliminarVenta() {
        int filaSeleccionada = tblsv.getSelectedRow();

        // Validar que se haya seleccionado una fila
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una venta de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el ID de la venta desde la primera columna de la tabla
        int idVentaAEliminar = (int) modeloTabla.getValueAt(filaSeleccionada, 0);

        // Confirmar la acción con el usuario
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar la venta seleccionada?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método del controlador para eliminar la venta
            if (VentaServicioController.eliminarVenta(idVentaAEliminar)) {
                JOptionPane.showMessageDialog(this, "Venta eliminada con éxito.");
                limpiarCampos();
                cargarVenta(); // Refrescar la tabla después de la eliminación
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la venta.");
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<UsuariosModel> combocajero;
    private javax.swing.JComboBox<String> comboesattus;
    private javax.swing.JComboBox<UsuariosModel> combolavador;
    private javax.swing.JComboBox<String> combopago;
    private javax.swing.JComboBox<ServiciosModel > comboservicio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblcajero;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblestatus;
    private javax.swing.JLabel lblestatus1;
    private javax.swing.JLabel lblestatus2;
    private javax.swing.JLabel lblestatus3;
    private javax.swing.JLabel lbllavador;
    private javax.swing.JLabel lblservicio;
    private javax.swing.JTable tblsv;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtminutos;
    private javax.swing.JTextField txtvehiculo;
    // End of variables declaration//GEN-END:variables

}
