/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.utxicotepec.autolavado.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.edu.utxicotepec.autolavado.Controller.ClientesController;
import mx.edu.utxicotepec.autolavado.Controller.VehiculoController;
import mx.edu.utxicotepec.autolavado.model.ClientesModel;
import mx.edu.utxicotepec.autolavado.model.VehiculoModel;

/**
 *
 * @author xLuisCM
 */
public class FrmVehiculos extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    int idVehiculo = 0;
    private int idVehiculoSeleccionado;

    /**
     * Creates new form FrmVehiculos
     */
    public FrmVehiculos() {
        super("Formulario Vehiculos", true, false, false, true);
        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);

        modeloTabla = new DefaultTableModel(new Object[]{"idVehiculo", "matricula", "marca", "modelo", "color", "year", "idCliente", "tipo"}, 0);

        initComponents();

        combotipo.addItem("Familiar");
        combotipo.addItem("Camioneta");
        combotipo.addItem("Minivan");
        combotipo.addItem("Camion");
        combotipo.addItem("Autobus");
        combotipo.addItem("Motocicleta");
        combotipo.addItem("Tsuro Tuneado");

        tblvehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblvehiculoMouseClicked(evt);
            }
        });

        tblvehiculos.setModel(modeloTabla);
        cargarVehiculo();
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblmatricula = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        lblmarca = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        lblmodelo = new javax.swing.JLabel();
        lblcolor = new javax.swing.JLabel();
        lblanio = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        txtanio = new javax.swing.JTextField();
        lbltipo = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        combocliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblvehiculos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Vehiculos");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        lblmatricula.setBackground(new java.awt.Color(0, 0, 255));
        lblmatricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblmatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblmatricula.setText("Matricula:");

        txtmatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtmatricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtmatricula.setPreferredSize(new java.awt.Dimension(15, 25));

        lblmarca.setBackground(new java.awt.Color(0, 0, 255));
        lblmarca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblmarca.setForeground(new java.awt.Color(0, 0, 0));
        lblmarca.setText("Marca:");

        txtmarca.setBackground(new java.awt.Color(255, 255, 255));
        txtmarca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(0, 0, 0));
        txtmarca.setPreferredSize(new java.awt.Dimension(15, 25));

        txtmodelo.setBackground(new java.awt.Color(255, 255, 255));
        txtmodelo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmodelo.setForeground(new java.awt.Color(0, 0, 0));
        txtmodelo.setPreferredSize(new java.awt.Dimension(15, 25));
        txtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodeloActionPerformed(evt);
            }
        });

        lblmodelo.setBackground(new java.awt.Color(0, 0, 255));
        lblmodelo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblmodelo.setForeground(new java.awt.Color(0, 0, 0));
        lblmodelo.setText("Modelo:");

        lblcolor.setBackground(new java.awt.Color(0, 0, 255));
        lblcolor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblcolor.setForeground(new java.awt.Color(0, 0, 0));
        lblcolor.setText("Color:");

        lblanio.setBackground(new java.awt.Color(0, 0, 255));
        lblanio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblanio.setForeground(new java.awt.Color(0, 0, 0));
        lblanio.setText("Año:");

        txtcolor.setBackground(new java.awt.Color(255, 255, 255));
        txtcolor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtcolor.setForeground(new java.awt.Color(0, 0, 0));
        txtcolor.setPreferredSize(new java.awt.Dimension(15, 25));
        txtcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolorActionPerformed(evt);
            }
        });

        txtanio.setBackground(new java.awt.Color(255, 255, 255));
        txtanio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtanio.setForeground(new java.awt.Color(0, 0, 0));
        txtanio.setMinimumSize(new java.awt.Dimension(15, 25));

        lbltipo.setBackground(new java.awt.Color(255, 255, 255));
        lbltipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbltipo.setForeground(new java.awt.Color(0, 0, 0));
        lbltipo.setText("Tipo:");

        lblcliente.setBackground(new java.awt.Color(255, 255, 255));
        lblcliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblcliente.setForeground(new java.awt.Color(0, 0, 0));
        lblcliente.setText("Cliente:");

        combotipo.setBackground(new java.awt.Color(255, 255, 255));
        combotipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combotipo.setForeground(new java.awt.Color(0, 0, 0));

        combocliente.setBackground(new java.awt.Color(255, 255, 255));
        combocliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        combocliente.setForeground(new java.awt.Color(0, 0, 0));

        tblvehiculos.setBackground(new java.awt.Color(255, 255, 255));
        tblvehiculos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblvehiculos.setForeground(new java.awt.Color(0, 0, 0));
        tblvehiculos.setModel(modeloTabla);
        jScrollPane2.setViewportView(tblvehiculos);

        jToolBar1.setRollover(true);

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Agregar.png")); // NOI18N
        btnnuevo.setText("Agregar");
        btnnuevo.setFocusable(false);
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnuevo);

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Guardar.png")); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnguardar);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Buscar.png")); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbuscar);

        btnmodificar.setBackground(new java.awt.Color(255, 255, 255));
        btnmodificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(0, 0, 0));
        btnmodificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\images\\Modificar.png")); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setFocusable(false);
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnmodificar);

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yazmin Ariana\\OneDrive\\Documentos\\NetBeansProjects\\iconos\\iconos\\Eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblmatricula)
                        .addComponent(lblmarca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblmodelo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblcolor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combocliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblanio)
                            .addComponent(lbltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtanio, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(combotipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmatricula)
                    .addComponent(lblanio)
                    .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmarca)
                    .addComponent(lbltipo)
                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodelo)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcliente)
                    .addComponent(combocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcolor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodeloActionPerformed

    private void txtcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        buscarVehiculo();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (eliminarvehiculo()) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");
            cargarClientes(); // Recarga los datos de la tabla para que el cambio sea visible
            limpiarcampos(); // Limpia el formulario después de la eliminación
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        agregarVehiculo();
        txtmatricula.setText("");
        txtmarca.setText("");
        txtmodelo.setText("");
        txtcolor.setText("");
        txtanio.setText("");
        combotipo.setSelectedIndex(0);
        combocliente.setSelectedIndex(0);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        if (modificarvehiculo()) {
            JOptionPane.showMessageDialog(this, "Vehículo modificado exitosamente.");
            cargarVehiculo(); // <-- ¡Aquí es donde recargas la tabla!
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el vehículo.");
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVehiculos().setVisible(true);
            }
        });

    }

    public void agregarVehiculo() {

        String matricula = txtmatricula.getText();
        String marca = txtmarca.getText();
        String modelo = txtmodelo.getText();
        String color = txtcolor.getText();
        String añostr = txtanio.getText();
        String tipo = (String) combotipo.getSelectedItem();

        if (combocliente.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente para asignar", "Error validacion", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idCliente = 0;

        if (combocliente.getSelectedItem() instanceof mx.edu.utxicotepec.autolavado.model.ClientesModel) {
            mx.edu.utxicotepec.autolavado.model.ClientesModel clienteSeleccionado = (mx.edu.utxicotepec.autolavado.model.ClientesModel) combocliente.getSelectedItem();
            idCliente = clienteSeleccionado.getIdCliente();
        } else {
            JOptionPane.showMessageDialog(this, "Error interno: El elemento seleccionado no es un Cliente valido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (matricula.isEmpty() || marca.isEmpty() || modelo.isEmpty() || color.isEmpty() || añostr.isEmpty() || tipo == null) {
            JOptionPane.showConfirmDialog(this, "Favor de ingresar los datos en las cajas de texto vacias.");
            return;
        }

        int año = 0;

        try {
            año = Integer.parseInt(añostr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser un numer valido", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        idVehiculo = 0;

        VehiculoModel nuevoVehiculo = new VehiculoModel(matricula, marca, modelo, color, año, idCliente, tipo);

        if (VehiculoController.insertarVehiculo(nuevoVehiculo)) {
            JOptionPane.showMessageDialog(this, "Vehiculo agregado exitosamente");
            txtmatricula.setText("");
            txtmarca.setText("");
            txtmodelo.setText("");
            txtcolor.setText("");
            txtanio.setText("");
            cargarVehiculo();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void cargarVehiculo() {
        modeloTabla.setRowCount(0);
        List<VehiculoModel> vehiculo = VehiculoController.mostrarTodos();
        for (VehiculoModel v : vehiculo) {
            modeloTabla.addRow(new Object[]{v.getIdVehiculo(), v.getMatricula(), v.getMarca(), v.getModelo(), v.getColor(), v.getAño(), v.getIdCliente(), v.getTipo()});
        }
    }

    public void cargarClientes() {
        List<ClientesModel> clientes = ClientesController.mostrarTodos();
        combocliente.removeAllItems();
        for (ClientesModel cliente : clientes) {
            combocliente.addItem(cliente);
        }
    }

    public void buscarVehiculo() {
        String terminoBusqueda = JOptionPane.showInputDialog(this, "Ingrese el modelo, marca o tipo", "Buscar vehiculo", JOptionPane.QUESTION_MESSAGE);

        if (terminoBusqueda == null || terminoBusqueda.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el modelo o marca, para buscar");
            return;
        }

        modeloTabla.setRowCount(0);

        List<VehiculoModel> vehiculoEncontrado = VehiculoController.buscarvehiculosPorTermino(terminoBusqueda);

        if (!vehiculoEncontrado.isEmpty()) {
            for (VehiculoModel v : vehiculoEncontrado) {
                modeloTabla.addRow(new Object[]{v.getIdVehiculo(), v.getMatricula(), v.getMarca(), v.getModelo(), v.getColor(), v.getAño(), v.getIdCliente(), v.getTipo()});
            }
            JOptionPane.showMessageDialog(this, vehiculoEncontrado.size() + "Vehiculo/s encontrado/s");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron vehiculos con esa matricula o marca");
        }
    }

    public void tblvehiculoMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tblvehiculos.getSelectedRow();
        if (fila != -1) {
            idVehiculoSeleccionado = (int) tblvehiculos.getValueAt(fila, 0);

            txtmatricula.setText(tblvehiculos.getValueAt(fila, 1).toString());
            txtmarca.setText(tblvehiculos.getValueAt(fila, 2).toString());
            txtmodelo.setText(tblvehiculos.getValueAt(fila, 3).toString());
            txtcolor.setText(tblvehiculos.getValueAt(fila, 4).toString());
            txtanio.setText(tblvehiculos.getValueAt(fila, 5).toString());

            String tipocli = tblvehiculos.getValueAt(fila, 6).toString();
            combocliente.setSelectedItem(tipocli);
            int idClienteDeLaFila = (int) tblvehiculos.getValueAt(fila, 6);
            for (int i = 0; i < combocliente.getItemCount(); i++) {
                ClientesModel cliente = combocliente.getItemAt(i);
                if (cliente.getIdCliente() == idClienteDeLaFila) {
                    combocliente.setSelectedItem(cliente);
                    break;
                }
            }

            String tipoveh = tblvehiculos.getValueAt(fila, 7).toString();
            combotipo.setSelectedItem(tipoveh);

        }
    }

    private boolean modificarvehiculo() {
        if (idVehiculoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar  un vehiculo para modificar");
            return false;
        }
        String matricula = txtmatricula.getText();
        String marca = txtmarca.getText();
        String modelo = txtmodelo.getText();
        String color = txtcolor.getText();

        int anio;

        try {
            anio = Integer.parseInt(txtanio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser un número válido.");
            return false;
        }

        ClientesModel clienteSeleccionado = (ClientesModel) combocliente.getSelectedItem();
        if (clienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
            return false;
        }
        int idCliente = clienteSeleccionado.getIdCliente();

        String tipo = (String) combotipo.getSelectedItem();

        if (marca.isEmpty() || modelo.isEmpty() || color.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar los campos");
            return false;
        }

        VehiculoModel vehiculoModificado = new VehiculoModel(
                idVehiculoSeleccionado,
                matricula,
                marca,
                modelo,
                color,
                anio,
                idCliente,
                tipo
        );
        return VehiculoController.modificarVehiculo(vehiculoModificado);
    }

    private void limpiarcampos() {
        txtanio.setText("");
        txtcolor.setText("");
        txtmarca.setText("");
        txtmatricula.setText("");
        txtmodelo.setText("");
    }

    public boolean eliminarvehiculo() {
        if (idVehiculoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cehiculo para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este vehiculo?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            return VehiculoController.eliminarvehiculo(idVehiculoSeleccionado);
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<mx.edu.utxicotepec.autolavado.model.ClientesModel> combocliente;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblanio;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JLabel lblcolor;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmatricula;
    private javax.swing.JLabel lblmodelo;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JTable tblvehiculos;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmatricula;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
